name: guestbook
type: 'php:8.1'
mounts:
    "/var": { source: service, source_path: var, service: files }
    "/public/uploads": { source: service, source_path: uploads, service: files  }
relationships:
    database: "database:postgresql"
runtime:
    extensions:
        # other extensions
        - pdo_pgsql
        # other extensions