name: guestbook
type: 'php:8.1'
mounts:
    "/var": { source: local, source_path: var }
    "/public/uploads": { source: local, source_path: uploads }
    service: files
relationships:
    database: "database:postgresql"
runtime:
    extensions:
        # other extensions
        - pdo_pgsql
        # other extensions